### ISSUE TITLE
technologyCard

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#11]
![technologycard](https://cloud.githubusercontent.com/assets/533339/11787579/9404fcc2-a273-11e5-9f31-3df61b922e18.png)

A first draft for the `expanded technologyCard` view.

## Present in

- #12 

## ToDo
- [ ] Create descriptions of functions
- [X] Better study of the buttons position
- [ ] Create a collapsed view
- [ ] Add & define context for views (Project view, Collection view & Technology view)
- [X] Add responsiveness to change default column width from 3 to 4.
- [X] Add icon for readiness and impact

---

### v0.1 

<img width="366" alt="screen shot 2015-12-08 at 7 20 08 pm" src="https://cloud.githubusercontent.com/assets/533339/11668887/b78df168-9de0-11e5-9f89-1d57c358ca80.png">

### v0.2 

![screen shot 2015-12-09 at 5 15 58 pm](https://cloud.githubusercontent.com/assets/533339/11696509/bd264a60-9e9b-11e5-98d6-912a48a6bdbc.png)

A more compact design with dropdown menu for main actions. Added a
horizontal bar (on top) to display the technology status (New, Draft,
Published)

**Comment by arthursoares** [comment]
# ToDo

- [ ] Create descriptions of functions
- [ ] Better study of the buttons position
- [ ] Create a collapsed view
- [ ] Add & define context for views (Project view, Collection view & Technology view)

**Comment by rafaelcorreiapoli** [comment]
Beautiful ! 
What is "AP 3" and "RD 4" ?

**Comment by michellzappa** [comment]
"RD 4" poderia ser "R: 4.43", indicando Readiness da tecnologia.
"AP 3" poderia ser "I: 2.65", indicando Impacto médio da tecnologia.
Valeu!

**Comment by arthursoares** [comment]
É isso que o @michellzappa falou. São os dois plugins que possuímos hoje. `Readiness` e `Impact`.

**Comment by rafaelcorreiapoli** [comment]
Arthur, fiquei com dúvidas. Esta é a tela de apresentação de uma tecnologia em específico ou é a tela aonde vemos a lista de tecnologias? (representando cada uma por um card, ao invez de uma tabela)

**Comment by rafaelcorreiapoli** [comment]
"Relatively cheap..."
Isto é a short description da descrição que estiver com o status Published, certo?

**Comment by arthursoares** [comment]
@rafaelcorreiapoli 

este é o `element` de uma carta de tecnologia. Essa carta vai ser exibida em algumas páginas que vão ser listadas aqui. É uma forma de eu organizar os templates. Por enquanto está presente apenas na tela #12 techList.

**Comment by michellzappa** [comment]
Nice!

**Comment by arthursoares** [comment]
@rafaelcorreiapoli olha a descrição da issue, ficou mais claro :)

**Comment by rafaelcorreiapoli** [comment]
@arthursoares 
Perfeito, já estou construindo :)
mas só para garantir, shortDescription na verdade é o shortText da description que estiver Published, certo?
No nosso schema não existe shortDescription (ou shortText) diretamente no objeto Technologie

**Comment by arthursoares** [comment]
@rafaelcorreiapoli yep! erro meu.

**Comment by arthursoares** [comment]
@rafaelcorreiapoli você viu o código no commit?

**Comment by rafaelcorreiapoli** [comment]
@arthursoares 
Não havia visto :( Vou utilizar!
Valeu

**Comment by arthursoares** [comment]
@rafaelcorreiapoli 
358028a79fef6bacea8056709ab545c62717a5d6  aqui tem o CSS editado. Tá no final :)

**Comment by arthursoares** [comment]
```css
.technology-box {
  padding: 0;
  border: 1px solid #e7eaec;
}
.technology-desc {
  padding: 10px;
  position: relative;
}
.technology-name {
  font-size: 16px;
  font-weight: 600;
  color: #676a6c;
  display: inline-block;
  margin: 2px 0 5px 0;
}
.technology-name:hover,
.technology-name:focus {
  color: #1ab394;
}

.addonsInfo {
  position: absolute;
  top: -30px;
  left: 0;
  text-align: center;
  float:left;
  width:100%;
}

.technologyTools {
position: absolute;
padding: 10px;
}

.techLabel {
  border-radius: 0px;
  border-image: none;
  border-style: solid solid none;
  border-width: 4px 0 0 0px;
}
```
