### ISSUE TITLE
Color label should reflect technology's status

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#162]
<img width="341" alt="screen shot 2016-03-25 at 6 48 24 pm" src="https://cloud.githubusercontent.com/assets/533339/14051373/3e8e6f84-f2ba-11e5-85bc-e734ec1b06e8.png">

label/btn-primary for published
label/btn-warning for Review
label/btn-danger for Draft

**Comment by michellzappa** [comment]
Nice one!

**Comment by rafaelcorreiapoli** [comment]
Created smart template for this at
73e38d2a7c0c94c245bbdb63060489dbf1ebe582
Closing...

**Comment by rafaelcorreiapoli** [comment]
I'm reopening because there may be another places where we should apply this template

**Comment by rafaelcorreiapoli** [comment]
Arthur can you give me the hex colors of those? I am using another configuration for Bootstrap classes (success, info, etc...)

**Comment by arthursoares** [comment]
I've fixed a lot of css classes for cards. check this; 8355af3 

here is the colors and classes

```less
// Basic Colors
@navy: #5186C5;       // Primary color
@dark-gray: #c2c2c2;  // Default color
@blue: #2FAEDA;       // Success color
@lazur: #8AC04F;      // Info color
@yellow: #f8ac59;     // Warrning color
@red: #ED5565;        // Danger color


.published,
.Published {
  border-color: @navy;
}

.review,
.Review {
  border-color: @yellow;
}

.draft,
.Draft {
  border-color: @red;
}
```
