### ISSUE TITLE
searchResults / cardLayout: Trim / limit amount of characters.

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#283]
<img width="944" alt="screen shot 2016-05-23 at 1 31 07 pm" src="https://cloud.githubusercontent.com/assets/533339/15469472/bb6599fc-20ea-11e6-95eb-eda0f31ec9a6.png">

Easy fix: I know that there is a css property that allows the amount of lines to be displayed.

https://css-tricks.com/line-clampin/

```css
      p {
        display: -webkit-box;
        overflow: hidden;
        -webkit-line-clamp: 5;
        -webkit-box-orient: vertical;
        text-overflow: ellipsis;
      }
```
